/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class au_edu_uq_itee_bt_Test */

#ifndef _Included_au_edu_uq_itee_bt_Test
#define _Included_au_edu_uq_itee_bt_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     au_edu_uq_itee_bt_Test
 * Method:    ping
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_au_edu_uq_itee_bt_Test_ping
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
