/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package org.be.textbe.bt.v1.textbt.resource.bt.grammar;

public class BtGrammarInformationProvider {
	
	public final static org.eclipse.emf.ecore.EStructuralFeature ANONYMOUS_FEATURE = org.eclipse.emf.ecore.EcoreFactory.eINSTANCE.createEAttribute();
	static {
		ANONYMOUS_FEATURE.setName("_");
	}
	
	public final static BtGrammarInformationProvider INSTANCE = new BtGrammarInformationProvider();
	
	private java.util.Set<String> keywords;
	
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_0_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("#RT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_0_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_0_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getSpecification().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.SPECIFICATION__REQUIREMENTS), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.PLUS, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_0_0_0_3 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_0_0_0_4 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getSpecification().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.SPECIFICATION__COMPONENTS), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.PLUS, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_0_0_0_5_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("#T", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_0_0_0_5_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_0_0_0_5_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getSpecification().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.SPECIFICATION__ROOT), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_0_0_0_5_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_0_0_0_5_0_0_0, BT_0_0_0_5_0_0_1, BT_0_0_0_5_0_0_2);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_0_0_0_5_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_0_0_0_5_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound BT_0_0_0_5 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound(BT_0_0_0_5_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.QUESTIONMARK);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_0_0_0_0, BT_0_0_0_1, BT_0_0_0_2, BT_0_0_0_3, BT_0_0_0_4, BT_0_0_0_5);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_0_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getSpecification(), BT_0_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_1_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getRequirement().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.REQUIREMENT__ID), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_1_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_1_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getRequirement().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.REQUIREMENT__NAME), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_1_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_1_0_0_0, BT_1_0_0_1, BT_1_0_0_2);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_1_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_1_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getRequirement(), BT_1_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_2_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("#C", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_2_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_2_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getComponent().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.COMPONENT__ID), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_2_0_0_3 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_2_0_0_4 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getComponent().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.COMPONENT__NAME), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtLineBreak BT_2_0_0_5 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtLineBreak(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_2_0_0_6 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getComponent().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.COMPONENT__BEHAVIOR), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_2_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_2_0_0_0, BT_2_0_0_1, BT_2_0_0_2, BT_2_0_0_3, BT_2_0_0_4, BT_2_0_0_5, BT_2_0_0_6);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_2_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_2_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getComponent(), BT_2_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_3_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("#SC", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_3_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_3_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getSystemComponent().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.SYSTEM_COMPONENT__ID), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_3_0_0_3 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_3_0_0_4 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getSystemComponent().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.SYSTEM_COMPONENT__NAME), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_3_0_0_5 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_3_0_0_6 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getSystemComponent().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.SYSTEM_COMPONENT__BEHAVIOR), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_3_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_3_0_0_0, BT_3_0_0_1, BT_3_0_0_2, BT_3_0_0_3, BT_3_0_0_4, BT_3_0_0_5, BT_3_0_0_6);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_3_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_3_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_3 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getSystemComponent(), BT_3_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_4_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("#E", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_4_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_4_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getEvent().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.EVENT__NUMBER), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_4_0_0_3 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_4_0_0_4 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getEvent().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.EVENT__NAME), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_4_0_0_5 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_4_0_0_6 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getEvent().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.EVENT__RELATIONS), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_4_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_4_0_0_0, BT_4_0_0_1, BT_4_0_0_2, BT_4_0_0_3, BT_4_0_0_4, BT_4_0_0_5, BT_4_0_0_6);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_4_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_4_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_4 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getEvent(), BT_4_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_5_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("#II", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_5_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_5_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getInternalInput().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.INTERNAL_INPUT__NUMBER), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_5_0_0_3 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_5_0_0_4 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getInternalInput().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.INTERNAL_INPUT__NAME), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_5_0_0_5 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_5_0_0_6 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getInternalInput().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.INTERNAL_INPUT__RELATIONS), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_5_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_5_0_0_0, BT_5_0_0_1, BT_5_0_0_2, BT_5_0_0_3, BT_5_0_0_4, BT_5_0_0_5, BT_5_0_0_6);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_5_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_5_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_5 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getInternalInput(), BT_5_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_6_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("#EI", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_6_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_6_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getExternalInput().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.EXTERNAL_INPUT__NUMBER), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_6_0_0_3 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_6_0_0_4 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getExternalInput().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.EXTERNAL_INPUT__NAME), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_6_0_0_5 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_6_0_0_6 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getExternalInput().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.EXTERNAL_INPUT__RELATIONS), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_6_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_6_0_0_0, BT_6_0_0_1, BT_6_0_0_2, BT_6_0_0_3, BT_6_0_0_4, BT_6_0_0_5, BT_6_0_0_6);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_6_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_6_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_6 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getExternalInput(), BT_6_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_7_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("#IO", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_7_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_7_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getInternalOutput().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.INTERNAL_OUTPUT__NUMBER), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_7_0_0_3 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_7_0_0_4 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getInternalOutput().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.INTERNAL_OUTPUT__NAME), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_7_0_0_5 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_7_0_0_6 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getInternalOutput().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.INTERNAL_OUTPUT__RELATIONS), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_7_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_7_0_0_0, BT_7_0_0_1, BT_7_0_0_2, BT_7_0_0_3, BT_7_0_0_4, BT_7_0_0_5, BT_7_0_0_6);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_7_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_7_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_7 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getInternalOutput(), BT_7_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_8_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("#EO", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_8_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_8_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getExternalOutput().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.EXTERNAL_OUTPUT__NUMBER), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_8_0_0_3 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_8_0_0_4 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getExternalOutput().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.EXTERNAL_OUTPUT__NAME), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_8_0_0_5 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_8_0_0_6 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getExternalOutput().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.EXTERNAL_OUTPUT__RELATIONS), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_8_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_8_0_0_0, BT_8_0_0_1, BT_8_0_0_2, BT_8_0_0_3, BT_8_0_0_4, BT_8_0_0_5, BT_8_0_0_6);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_8_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_8_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_8 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getExternalOutput(), BT_8_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_9_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("#S", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_9_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_9_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getStateRealization().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.STATE_REALIZATION__NUMBER), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_9_0_0_3 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_9_0_0_4 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getStateRealization().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.STATE_REALIZATION__NAME), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_9_0_0_5 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_9_0_0_6_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("[", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_9_0_0_6_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getStateRealization().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.STATE_REALIZATION__QUALIFIER), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_9_0_0_6_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("]", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_9_0_0_6_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_9_0_0_6_0_0_0, BT_9_0_0_6_0_0_1, BT_9_0_0_6_0_0_2);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_9_0_0_6_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_9_0_0_6_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound BT_9_0_0_6 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound(BT_9_0_0_6_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.QUESTIONMARK);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_9_0_0_7 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getStateRealization().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.STATE_REALIZATION__RELATIONS), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_9_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_9_0_0_0, BT_9_0_0_1, BT_9_0_0_2, BT_9_0_0_3, BT_9_0_0_4, BT_9_0_0_5, BT_9_0_0_6, BT_9_0_0_7);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_9_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_9_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_9 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getStateRealization(), BT_9_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_10_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("#AR", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_10_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_10_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getAttributeRealization().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.ATTRIBUTE_REALIZATION__NUMBER), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_10_0_0_3 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_10_0_0_4 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getAttributeRealization().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.ATTRIBUTE_REALIZATION__NAME), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_10_0_0_5 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_10_0_0_6 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getAttributeRealization().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.ATTRIBUTE_REALIZATION__RELATIONS), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_10_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_10_0_0_0, BT_10_0_0_1, BT_10_0_0_2, BT_10_0_0_3, BT_10_0_0_4, BT_10_0_0_5, BT_10_0_0_6);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_10_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_10_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_10 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getAttributeRealization(), BT_10_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_11_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("#L", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_11_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_11_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getSelection().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.SELECTION__NUMBER), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_11_0_0_3 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_11_0_0_4 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getSelection().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.SELECTION__NAME), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_11_0_0_5 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_11_0_0_6 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getSelection().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.SELECTION__RELATIONS), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_11_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_11_0_0_0, BT_11_0_0_1, BT_11_0_0_2, BT_11_0_0_3, BT_11_0_0_4, BT_11_0_0_5, BT_11_0_0_6);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_11_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_11_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_11 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getSelection(), BT_11_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_12_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("#G", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_12_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_12_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getGuard().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.GUARD__NUMBER), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_12_0_0_3 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_12_0_0_4 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getGuard().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.GUARD__NAME), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_12_0_0_5 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_12_0_0_6 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getGuard().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.GUARD__RELATIONS), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_12_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_12_0_0_0, BT_12_0_0_1, BT_12_0_0_2, BT_12_0_0_3, BT_12_0_0_4, BT_12_0_0_5, BT_12_0_0_6);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_12_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_12_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_12 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getGuard(), BT_12_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_13_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("#A", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_13_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_13_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getAssertion().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.ASSERTION__NUMBER), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_13_0_0_3 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_13_0_0_4 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getAssertion().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.ASSERTION__NAME), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_13_0_0_5 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_13_0_0_6 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getAssertion().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.ASSERTION__RELATIONS), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_13_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_13_0_0_0, BT_13_0_0_1, BT_13_0_0_2, BT_13_0_0_3, BT_13_0_0_4, BT_13_0_0_5, BT_13_0_0_6);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_13_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_13_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_13 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getAssertion(), BT_13_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_14_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("#R", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtBooleanTerminal BT_14_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtBooleanTerminal(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getWhat().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.WHAT__MULTI_LEVEL), "/", "", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_14_0_0_2_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("/", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_14_0_0_2_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_14_0_0_2_0_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_14_0_0_2_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_14_0_0_2_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound BT_14_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound(BT_14_0_0_2_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_14_0_0_3 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("What", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_14_0_0_4 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getWhat().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.WHAT__OBSERVATION), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_14_0_0_5_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getWhat().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.WHAT__OBSERVATION), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_14_0_0_5_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_14_0_0_5_0_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_14_0_0_5_0_1_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("/", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_14_0_0_5_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_14_0_0_5_0_1_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_14_0_0_5_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_14_0_0_5_0_0, BT_14_0_0_5_0_1);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound BT_14_0_0_5 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound(BT_14_0_0_5_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_14_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_14_0_0_0, BT_14_0_0_1, BT_14_0_0_2, BT_14_0_0_3, BT_14_0_0_4, BT_14_0_0_5);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_14_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_14_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_14 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getWhat(), BT_14_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_15_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("#R", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtBooleanTerminal BT_15_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtBooleanTerminal(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getWho().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.WHO__MULTI_LEVEL), "/", "", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_15_0_0_2_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("/", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_15_0_0_2_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_15_0_0_2_0_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_15_0_0_2_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_15_0_0_2_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound BT_15_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound(BT_15_0_0_2_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_15_0_0_3 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("Who", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_15_0_0_4 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getWho().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.WHO__PERSON), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_15_0_0_5_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getWho().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.WHO__PERSON), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_15_0_0_5_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_15_0_0_5_0_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_15_0_0_5_0_1_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("/", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_15_0_0_5_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_15_0_0_5_0_1_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_15_0_0_5_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_15_0_0_5_0_0, BT_15_0_0_5_0_1);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound BT_15_0_0_5 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound(BT_15_0_0_5_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_15_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_15_0_0_0, BT_15_0_0_1, BT_15_0_0_2, BT_15_0_0_3, BT_15_0_0_4, BT_15_0_0_5);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_15_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_15_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_15 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getWho(), BT_15_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_16_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("#R", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtBooleanTerminal BT_16_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtBooleanTerminal(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getWhy().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.WHY__MULTI_LEVEL), "/", "", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_16_0_0_2_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("/", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_16_0_0_2_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_16_0_0_2_0_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_16_0_0_2_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_16_0_0_2_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound BT_16_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound(BT_16_0_0_2_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_16_0_0_3 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("Why", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_16_0_0_4 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getWhy().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.WHY__REASON), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_16_0_0_5_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getWhy().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.WHY__REASON), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_16_0_0_5_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_16_0_0_5_0_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_16_0_0_5_0_1_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("/", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_16_0_0_5_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_16_0_0_5_0_1_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_16_0_0_5_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_16_0_0_5_0_0, BT_16_0_0_5_0_1);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound BT_16_0_0_5 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound(BT_16_0_0_5_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_16_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_16_0_0_0, BT_16_0_0_1, BT_16_0_0_2, BT_16_0_0_3, BT_16_0_0_4, BT_16_0_0_5);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_16_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_16_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_16 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getWhy(), BT_16_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_17_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("#R", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtBooleanTerminal BT_17_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtBooleanTerminal(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getHow().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.HOW__MULTI_LEVEL), "/", "", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_17_0_0_2_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("/", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_17_0_0_2_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_17_0_0_2_0_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_17_0_0_2_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_17_0_0_2_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound BT_17_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound(BT_17_0_0_2_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_17_0_0_3 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("How", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_17_0_0_4 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getHow().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.HOW__MEANS), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_17_0_0_5_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getHow().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.HOW__MEANS), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_17_0_0_5_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_17_0_0_5_0_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_17_0_0_5_0_1_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("/", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_17_0_0_5_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_17_0_0_5_0_1_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_17_0_0_5_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_17_0_0_5_0_0, BT_17_0_0_5_0_1);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound BT_17_0_0_5 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound(BT_17_0_0_5_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_17_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_17_0_0_0, BT_17_0_0_1, BT_17_0_0_2, BT_17_0_0_3, BT_17_0_0_4, BT_17_0_0_5);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_17_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_17_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_17 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getHow(), BT_17_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_18_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("#R", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtBooleanTerminal BT_18_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtBooleanTerminal(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getWhere().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.WHERE__MULTI_LEVEL), "/", "", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_18_0_0_2_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("/", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_18_0_0_2_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_18_0_0_2_0_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_18_0_0_2_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_18_0_0_2_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound BT_18_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound(BT_18_0_0_2_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_18_0_0_3 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("Where", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_18_0_0_4 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getWhere().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.WHERE__PLACE), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_18_0_0_5_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getWhere().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.WHERE__PLACE), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_18_0_0_5_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_18_0_0_5_0_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_18_0_0_5_0_1_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("/", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_18_0_0_5_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_18_0_0_5_0_1_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_18_0_0_5_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_18_0_0_5_0_0, BT_18_0_0_5_0_1);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound BT_18_0_0_5 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound(BT_18_0_0_5_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_18_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_18_0_0_0, BT_18_0_0_1, BT_18_0_0_2, BT_18_0_0_3, BT_18_0_0_4, BT_18_0_0_5);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_18_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_18_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_18 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getWhere(), BT_18_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_19_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("#R", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtBooleanTerminal BT_19_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtBooleanTerminal(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getWhen().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.WHEN__MULTI_LEVEL), "/", "", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_19_0_0_2_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("/", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_19_0_0_2_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_19_0_0_2_0_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_19_0_0_2_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_19_0_0_2_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound BT_19_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound(BT_19_0_0_2_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_19_0_0_3 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("When", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_19_0_0_4 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getWhen().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.WHEN__TIME), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_19_0_0_5_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getWhen().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.WHEN__TIME), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_19_0_0_5_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_19_0_0_5_0_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_19_0_0_5_0_1_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("/", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_19_0_0_5_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_19_0_0_5_0_1_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_19_0_0_5_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_19_0_0_5_0_0, BT_19_0_0_5_0_1);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound BT_19_0_0_5 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound(BT_19_0_0_5_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_19_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_19_0_0_0, BT_19_0_0_1, BT_19_0_0_2, BT_19_0_0_3, BT_19_0_0_4, BT_19_0_0_5);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_19_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_19_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_19 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getWhen(), BT_19_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_20_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("{", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_20_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_20_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getAtomic().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.ATOMIC__STEPS), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_20_0_0_3_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword(";;", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_20_0_0_3_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getAtomic().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.ATOMIC__STEPS), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_20_0_0_3_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_20_0_0_3_0_0_0, BT_20_0_0_3_0_0_1);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_20_0_0_3_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_20_0_0_3_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound BT_20_0_0_3 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound(BT_20_0_0_3_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_20_0_0_4 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_20_0_0_5 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getAtomic().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.ATOMIC__CHILD), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.QUESTIONMARK, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_20_0_0_6 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("}", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_20_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_20_0_0_0, BT_20_0_0_1, BT_20_0_0_2, BT_20_0_0_3, BT_20_0_0_4, BT_20_0_0_5, BT_20_0_0_6);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_20_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_20_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_20 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getAtomic(), BT_20_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_21_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("{", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_21_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_21_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getInterleaving().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.INTERLEAVING__STEPS), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_21_0_0_3_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword(";", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_21_0_0_3_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getInterleaving().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.INTERLEAVING__STEPS), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_21_0_0_3_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_21_0_0_3_0_0_0, BT_21_0_0_3_0_0_1);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_21_0_0_3_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_21_0_0_3_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound BT_21_0_0_3 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound(BT_21_0_0_3_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_21_0_0_4 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_21_0_0_5 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getInterleaving().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.INTERLEAVING__CHILD), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.QUESTIONMARK, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_21_0_0_6 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("}", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_21_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_21_0_0_0, BT_21_0_0_1, BT_21_0_0_2, BT_21_0_0_3, BT_21_0_0_4, BT_21_0_0_5, BT_21_0_0_6);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_21_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_21_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_21 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getInterleaving(), BT_21_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_22_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("#N", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_22_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_22_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("{", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_22_0_0_3 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getAlternative().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.ALTERNATIVE__CHOICES), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_22_0_0_4_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getAlternative().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.ALTERNATIVE__CHOICES), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_22_0_0_4_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_22_0_0_4_0_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_22_0_0_4_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_22_0_0_4_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound BT_22_0_0_4 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound(BT_22_0_0_4_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_22_0_0_5 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("}", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_22_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_22_0_0_0, BT_22_0_0_1, BT_22_0_0_2, BT_22_0_0_3, BT_22_0_0_4, BT_22_0_0_5);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_22_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_22_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_22 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getAlternative(), BT_22_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_23_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("#P", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace BT_23_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtWhiteSpace(1, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_23_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("{", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_23_0_0_3 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getParallel().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.PARALLEL__PROCESSES), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_23_0_0_4_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getParallel().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.PARALLEL__PROCESSES), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_23_0_0_4_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_23_0_0_4_0_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_23_0_0_4_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_23_0_0_4_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound BT_23_0_0_4 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound(BT_23_0_0_4_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_23_0_0_5 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("}", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_23_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_23_0_0_0, BT_23_0_0_1, BT_23_0_0_2, BT_23_0_0_3, BT_23_0_0_4, BT_23_0_0_5);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_23_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_23_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_23 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getParallel(), BT_23_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_24_0_0_0_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("'", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_24_0_0_0_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getNode().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.NODE__LABEL), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_24_0_0_0_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("'", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_24_0_0_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_24_0_0_0_0_0_0, BT_24_0_0_0_0_0_1, BT_24_0_0_0_0_0_2);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_24_0_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_24_0_0_0_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound BT_24_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound(BT_24_0_0_0_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.QUESTIONMARK);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtBooleanTerminal BT_24_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtBooleanTerminal(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getNode().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.NODE__SHOW_TAG), "show", "hide", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.QUESTIONMARK, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment BT_24_0_0_2_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtContainment(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getNode().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.NODE__TRACEABILITY), org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_24_0_0_2_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getNode().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.NODE__BEHAVIOR), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_24_0_0_2_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_24_0_0_2_0_0_0, BT_24_0_0_2_0_0_1);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_24_0_0_2_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_24_0_0_2_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound BT_24_0_0_2 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCompound(BT_24_0_0_2_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_24_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_24_0_0_0, BT_24_0_0_1, BT_24_0_0_2);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword BT_24_0_1_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword("_", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtEnumerationTerminal BT_24_0_1_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtEnumerationTerminal(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getNode().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.NODE__OPERATOR), new String[] {"Normal", "", "Reversion", "^", "Synchronization", "=", "Reference", "=>", "BranchKill", "--", "May", "%", "StartNew", "^^", "Xor", "XOR", "Disjunction", "|", "Conjunction", "&", }, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.QUESTIONMARK, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_24_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_24_0_1_0, BT_24_0_1_1);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_24_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_24_0_0, BT_24_0_1);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_24 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getNode(), BT_24_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder BT_25_0_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtPlaceholder(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getTraceabilityLink().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.TRACEABILITY_LINK__REQUIREMENT), "TEXT", org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.STAR, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtEnumerationTerminal BT_25_0_0_1 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtEnumerationTerminal(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getTraceabilityLink().getEStructuralFeature(org.be.textbe.bt.v1.textbt.TextbtPackage.TRACEABILITY_LINK__STATUS), new String[] {"Original", "", "Implied", "+", "Missing", "-", "Updated", "++", "Deleted", "--", "Refined", "+-", }, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.QUESTIONMARK, 0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence BT_25_0_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSequence(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_25_0_0_0, BT_25_0_0_1);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice BT_25_0 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtChoice(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE, BT_25_0_0);
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule BT_25 = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule(org.be.textbe.bt.v1.textbt.TextbtPackage.eINSTANCE.getTraceabilityLink(), BT_25_0, org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtCardinality.ONE);
	
	public final static org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule[] RULES = new org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule[] {
		BT_0,
		BT_1,
		BT_2,
		BT_3,
		BT_4,
		BT_5,
		BT_6,
		BT_7,
		BT_8,
		BT_9,
		BT_10,
		BT_11,
		BT_12,
		BT_13,
		BT_14,
		BT_15,
		BT_16,
		BT_17,
		BT_18,
		BT_19,
		BT_20,
		BT_21,
		BT_22,
		BT_23,
		BT_24,
		BT_25,
	};
	
	/**
	 * Returns all keywords of the grammar. This includes all literals for boolean and
	 * enumeration terminals.
	 */
	public java.util.Set<String> getKeywords() {
		if (this.keywords == null) {
			this.keywords = new java.util.LinkedHashSet<String>();
			for (org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtRule rule : RULES) {
				findKeywords(rule, this.keywords);
			}
		}
		return keywords;
	}
	
	/**
	 * Finds all keywords in the given element and its children and adds them to the
	 * set. This includes all literals for boolean and enumeration terminals.
	 */
	private void findKeywords(org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSyntaxElement element, java.util.Set<String> keywords) {
		if (element instanceof org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword) {
			keywords.add(((org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtKeyword) element).getValue());
		} else if (element instanceof org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtBooleanTerminal) {
			keywords.add(((org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtBooleanTerminal) element).getTrueLiteral());
			keywords.add(((org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtBooleanTerminal) element).getFalseLiteral());
		} else if (element instanceof org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtEnumerationTerminal) {
			org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtEnumerationTerminal terminal = (org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtEnumerationTerminal) element;
			for (String key : terminal.getLiteralMapping().keySet()) {
				keywords.add(key);
			}
		}
		for (org.be.textbe.bt.v1.textbt.resource.bt.grammar.BtSyntaxElement child : element.getChildren()) {
			findKeywords(child, this.keywords);
		}
	}
	
}
