/*
 * au_edu_uq_itee_bt_Test.c
 *
 *  Created on: 06/11/2012
 *      Author: uqjsuss
 */

#include <stdio.h>
#include "au_edu_uq_itee_bt_Test.h"   // this header file was generated by javah
JNIEXPORT jstring JNICALL Java_au_edu_uq_itee_bt_Test_ping(
		JNIEnv* env, jobject obj, jstring str) {

	jstring result;
	char returnString[5] = "DONE";
	result = (*env)->NewStringUTF(env, returnString);
	free(returnString);
	printf("Hello gaga!\n");
	return result;
}
