/*
* generated by Xtext
*/
package org.be.textbe.bt2sal2.xtext.sal.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.be.textbe.bt2sal2.xtext.sal.services.SalGrammarAccess;

public class SalParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SalGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS");
	}
	
	@Override
	protected org.be.textbe.bt2sal2.xtext.sal.parser.antlr.internal.InternalSalParser createParser(XtextTokenStream stream) {
		return new org.be.textbe.bt2sal2.xtext.sal.parser.antlr.internal.InternalSalParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Context";
	}
	
	public SalGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SalGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
