/* DO NOT EDIT THIS FILE - it is machine generated */
#include <C:\Users\uqnyatap\java files\jni.h>
/* Header for class Test */

#ifndef _Included_Test
#define _Included_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Test
 * Method:    translatetoSAL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Test_translatetoSAL
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
