/**
 * <copyright>
 * </copyright>
 *
 * 
 */
package org.be.textbe.ct.textct.resource.ct.grammar;

/**
 * This class provides the follow sets for all terminals of the grammar. These
 * sets are used during code completion.
 */
public class CtFollowSetProvider {
	
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_0 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedCsString(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_9_0_0_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_1 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedCsString(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_11_0_0_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_2 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedCsString(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_13_0_0_0_0_0_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_3 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedCsString(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_13_0_0_1_0_0_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_4 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedCsString(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_13_0_0_2_0_0_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_5 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedCsString(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_1_0_0_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_6 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedStructuralFeature(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_8_0_0_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_7 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedCsString(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_2_0_0_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_8 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedStructuralFeature(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_2_0_0_1);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_9 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedCsString(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_3_0_0_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_10 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedCsString(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_4_0_0_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_11 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedCsString(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_5_0_0_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_12 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedCsString(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_6_0_0_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_13 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedCsString(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_7_0_0_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_14 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedCsString(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_5_0_0_3);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_15 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedCsString(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_6_0_0_3);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_16 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedCsString(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_7_0_0_3);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_17 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedStructuralFeature(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_3_0_0_1);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_18 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedStructuralFeature(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_4_0_0_1);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_19 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedCsString(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_5_0_0_1);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_20 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedCsString(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_6_0_0_1);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_21 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedCsString(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_7_0_0_1);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_22 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedStructuralFeature(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_10_0_0_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_23 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedCsString(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_10_0_0_1);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_24 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedStructuralFeature(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_10_0_0_2);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_25 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedStructuralFeature(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_12_0_0_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_26 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedStructuralFeature(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_12_0_0_1_0_0_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_27 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedStructuralFeature(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_12_0_0_1_0_1_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_28 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedStructuralFeature(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_12_0_0_1_0_2_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_29 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedStructuralFeature(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_12_0_0_1_0_3_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_30 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedStructuralFeature(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_14_0_0_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_31 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedStructuralFeature(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_15_0_0_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_32 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedStructuralFeature(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_14_0_0_1_0_0_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_33 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedStructuralFeature(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_14_0_0_1_0_1_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_34 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedStructuralFeature(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_14_0_0_1_0_2_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_35 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedStructuralFeature(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_14_0_0_1_0_3_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_36 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedStructuralFeature(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_15_0_0_1_0_0_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_37 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedStructuralFeature(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_15_0_0_1_0_1_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_38 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedStructuralFeature(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_15_0_0_1_0_2_0);
	public final static org.be.textbe.ct.textct.resource.ct.ICtExpectedElement TERMINAL_39 = new org.be.textbe.ct.textct.resource.ct.mopp.CtExpectedStructuralFeature(org.be.textbe.ct.textct.resource.ct.grammar.CtGrammarInformationProvider.CT_15_0_0_1_0_3_0);
	
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_0 = org.be.textbe.ct.textct.TextctPackage.eINSTANCE.getTextCT().getEStructuralFeature(org.be.textbe.ct.textct.TextctPackage.TEXT_CT__OPTIONS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_1 = org.be.textbe.ct.textct.TextctPackage.eINSTANCE.getTextCT().getEStructuralFeature(org.be.textbe.ct.textct.TextctPackage.TEXT_CT__REQUIREMENTS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_2 = org.be.textbe.ct.textct.TextctPackage.eINSTANCE.getTextCT().getEStructuralFeature(org.be.textbe.ct.textct.TextctPackage.TEXT_CT__COMPONENTS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_3 = org.be.textbe.ct.textct.TextctPackage.eINSTANCE.getTextCT().getEStructuralFeature(org.be.textbe.ct.textct.TextctPackage.TEXT_CT__COMPOSITION_TREE);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_4 = org.be.textbe.ct.textct.TextctPackage.eINSTANCE.getCompositionTree().getEStructuralFeature(org.be.textbe.ct.textct.TextctPackage.COMPOSITION_TREE__ROOT_NODE);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_5 = org.be.textbe.ct.textct.TextctPackage.eINSTANCE.getAbstractNode().getEStructuralFeature(org.be.textbe.ct.textct.TextctPackage.ABSTRACT_NODE__CHILD_NODE);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_6 = org.be.textbe.ct.textct.TextctPackage.eINSTANCE.getAbstractBlock().getEStructuralFeature(org.be.textbe.ct.textct.TextctPackage.ABSTRACT_BLOCK__CHILD_NODE);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_7 = org.be.textbe.ct.textct.TextctPackage.eINSTANCE.getOptionList().getEStructuralFeature(org.be.textbe.ct.textct.TextctPackage.OPTION_LIST__OPTIONS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_8 = org.be.textbe.ct.textct.TextctPackage.eINSTANCE.getRequirementList().getEStructuralFeature(org.be.textbe.ct.textct.TextctPackage.REQUIREMENT_LIST__REQUIREMENTS);
	public final static org.eclipse.emf.ecore.EStructuralFeature FEATURE_9 = org.be.textbe.ct.textct.TextctPackage.eINSTANCE.getComponentList().getEStructuralFeature(org.be.textbe.ct.textct.TextctPackage.COMPONENT_LIST__COMPONENTS);
	
	public final static org.eclipse.emf.ecore.EStructuralFeature[] EMPTY_FEATURE_ARRAY = new org.eclipse.emf.ecore.EStructuralFeature[0];
	
	public static void wire0() {
		TERMINAL_5.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_4, });
		TERMINAL_7.addFollower(TERMINAL_8, EMPTY_FEATURE_ARRAY);
		TERMINAL_8.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_8.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_8.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_8.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_8.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_8.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_8.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_8.addFollower(TERMINAL_14, EMPTY_FEATURE_ARRAY);
		TERMINAL_8.addFollower(TERMINAL_15, EMPTY_FEATURE_ARRAY);
		TERMINAL_8.addFollower(TERMINAL_16, EMPTY_FEATURE_ARRAY);
		TERMINAL_9.addFollower(TERMINAL_17, EMPTY_FEATURE_ARRAY);
		TERMINAL_17.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_17.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_17.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_17.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_17.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_17.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_17.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_17.addFollower(TERMINAL_14, EMPTY_FEATURE_ARRAY);
		TERMINAL_17.addFollower(TERMINAL_15, EMPTY_FEATURE_ARRAY);
		TERMINAL_17.addFollower(TERMINAL_16, EMPTY_FEATURE_ARRAY);
		TERMINAL_10.addFollower(TERMINAL_18, EMPTY_FEATURE_ARRAY);
		TERMINAL_18.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_18.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_18.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_18.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_18.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_18.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_18.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_18.addFollower(TERMINAL_14, EMPTY_FEATURE_ARRAY);
		TERMINAL_18.addFollower(TERMINAL_15, EMPTY_FEATURE_ARRAY);
		TERMINAL_18.addFollower(TERMINAL_16, EMPTY_FEATURE_ARRAY);
		TERMINAL_11.addFollower(TERMINAL_19, EMPTY_FEATURE_ARRAY);
		TERMINAL_19.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_19.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_19.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_19.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_14.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_14.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_14.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_14.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_14.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_14.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_14.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_14.addFollower(TERMINAL_14, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_15, EMPTY_FEATURE_ARRAY);
		TERMINAL_14.addFollower(TERMINAL_16, EMPTY_FEATURE_ARRAY);
		TERMINAL_12.addFollower(TERMINAL_20, EMPTY_FEATURE_ARRAY);
		TERMINAL_20.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_20.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_20.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_20.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_15.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_15.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_15.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_15.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_15.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_15.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_15.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_15.addFollower(TERMINAL_14, EMPTY_FEATURE_ARRAY);
		TERMINAL_15.addFollower(TERMINAL_15, EMPTY_FEATURE_ARRAY);
		TERMINAL_15.addFollower(TERMINAL_16, EMPTY_FEATURE_ARRAY);
		TERMINAL_13.addFollower(TERMINAL_21, EMPTY_FEATURE_ARRAY);
		TERMINAL_21.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_21.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_21.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_21.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_6, });
		TERMINAL_16.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_16.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_16.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_16.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_16.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_16.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_16.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_16.addFollower(TERMINAL_14, EMPTY_FEATURE_ARRAY);
		TERMINAL_16.addFollower(TERMINAL_15, EMPTY_FEATURE_ARRAY);
		TERMINAL_16.addFollower(TERMINAL_16, EMPTY_FEATURE_ARRAY);
		TERMINAL_6.addFollower(TERMINAL_7, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_6.addFollower(TERMINAL_9, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_6.addFollower(TERMINAL_10, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_6.addFollower(TERMINAL_11, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_6.addFollower(TERMINAL_12, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_6.addFollower(TERMINAL_13, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_6.addFollower(TERMINAL_6, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_5, });
		TERMINAL_6.addFollower(TERMINAL_14, EMPTY_FEATURE_ARRAY);
		TERMINAL_6.addFollower(TERMINAL_15, EMPTY_FEATURE_ARRAY);
		TERMINAL_6.addFollower(TERMINAL_16, EMPTY_FEATURE_ARRAY);
		TERMINAL_0.addFollower(TERMINAL_22, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_22.addFollower(TERMINAL_23, EMPTY_FEATURE_ARRAY);
		TERMINAL_23.addFollower(TERMINAL_24, EMPTY_FEATURE_ARRAY);
		TERMINAL_24.addFollower(TERMINAL_22, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_7, });
		TERMINAL_24.addFollower(TERMINAL_1, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_1, });
		TERMINAL_24.addFollower(TERMINAL_2, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_24.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_24.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_24.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_1.addFollower(TERMINAL_25, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_25.addFollower(TERMINAL_26, EMPTY_FEATURE_ARRAY);
		TERMINAL_25.addFollower(TERMINAL_27, EMPTY_FEATURE_ARRAY);
		TERMINAL_25.addFollower(TERMINAL_28, EMPTY_FEATURE_ARRAY);
		TERMINAL_25.addFollower(TERMINAL_29, EMPTY_FEATURE_ARRAY);
		TERMINAL_26.addFollower(TERMINAL_25, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_26.addFollower(TERMINAL_2, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_26.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_26.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_26.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_27.addFollower(TERMINAL_25, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_27.addFollower(TERMINAL_2, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_27.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_27.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_27.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_28.addFollower(TERMINAL_25, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_28.addFollower(TERMINAL_2, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_28.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_28.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_28.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_29.addFollower(TERMINAL_25, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_8, });
		TERMINAL_29.addFollower(TERMINAL_2, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_29.addFollower(TERMINAL_3, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_29.addFollower(TERMINAL_4, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_2, });
		TERMINAL_29.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_2.addFollower(TERMINAL_30, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, });
		TERMINAL_2.addFollower(TERMINAL_31, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, });
		TERMINAL_3.addFollower(TERMINAL_31, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, });
		TERMINAL_4.addFollower(TERMINAL_30, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, });
		TERMINAL_4.addFollower(TERMINAL_31, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_9, });
		TERMINAL_30.addFollower(TERMINAL_32, EMPTY_FEATURE_ARRAY);
		TERMINAL_30.addFollower(TERMINAL_33, EMPTY_FEATURE_ARRAY);
		TERMINAL_30.addFollower(TERMINAL_34, EMPTY_FEATURE_ARRAY);
		TERMINAL_30.addFollower(TERMINAL_35, EMPTY_FEATURE_ARRAY);
		TERMINAL_32.addFollower(TERMINAL_2, EMPTY_FEATURE_ARRAY);
		TERMINAL_32.addFollower(TERMINAL_3, EMPTY_FEATURE_ARRAY);
		TERMINAL_32.addFollower(TERMINAL_4, EMPTY_FEATURE_ARRAY);
		TERMINAL_32.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_33.addFollower(TERMINAL_2, EMPTY_FEATURE_ARRAY);
		TERMINAL_33.addFollower(TERMINAL_3, EMPTY_FEATURE_ARRAY);
		TERMINAL_33.addFollower(TERMINAL_4, EMPTY_FEATURE_ARRAY);
		TERMINAL_33.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_34.addFollower(TERMINAL_2, EMPTY_FEATURE_ARRAY);
		TERMINAL_34.addFollower(TERMINAL_3, EMPTY_FEATURE_ARRAY);
		TERMINAL_34.addFollower(TERMINAL_4, EMPTY_FEATURE_ARRAY);
		TERMINAL_34.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_35.addFollower(TERMINAL_2, EMPTY_FEATURE_ARRAY);
		TERMINAL_35.addFollower(TERMINAL_3, EMPTY_FEATURE_ARRAY);
		TERMINAL_35.addFollower(TERMINAL_4, EMPTY_FEATURE_ARRAY);
		TERMINAL_35.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_31.addFollower(TERMINAL_36, EMPTY_FEATURE_ARRAY);
		TERMINAL_31.addFollower(TERMINAL_37, EMPTY_FEATURE_ARRAY);
		TERMINAL_31.addFollower(TERMINAL_38, EMPTY_FEATURE_ARRAY);
		TERMINAL_31.addFollower(TERMINAL_39, EMPTY_FEATURE_ARRAY);
		TERMINAL_36.addFollower(TERMINAL_2, EMPTY_FEATURE_ARRAY);
		TERMINAL_36.addFollower(TERMINAL_3, EMPTY_FEATURE_ARRAY);
		TERMINAL_36.addFollower(TERMINAL_4, EMPTY_FEATURE_ARRAY);
		TERMINAL_36.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_37.addFollower(TERMINAL_2, EMPTY_FEATURE_ARRAY);
		TERMINAL_37.addFollower(TERMINAL_3, EMPTY_FEATURE_ARRAY);
		TERMINAL_37.addFollower(TERMINAL_4, EMPTY_FEATURE_ARRAY);
		TERMINAL_37.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_38.addFollower(TERMINAL_2, EMPTY_FEATURE_ARRAY);
		TERMINAL_38.addFollower(TERMINAL_3, EMPTY_FEATURE_ARRAY);
		TERMINAL_38.addFollower(TERMINAL_4, EMPTY_FEATURE_ARRAY);
		TERMINAL_38.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
		TERMINAL_39.addFollower(TERMINAL_2, EMPTY_FEATURE_ARRAY);
		TERMINAL_39.addFollower(TERMINAL_3, EMPTY_FEATURE_ARRAY);
		TERMINAL_39.addFollower(TERMINAL_4, EMPTY_FEATURE_ARRAY);
		TERMINAL_39.addFollower(TERMINAL_5, new org.eclipse.emf.ecore.EStructuralFeature[] {FEATURE_3, });
	}
	// wire the terminals
	static {
		wire0();
	}
}
