/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_be_textbe_bt2sal_v0_Bt2Sal */

#ifndef _Included_org_be_textbe_bt2sal_v0_Bt2Sal
#define _Included_org_be_textbe_bt2sal_v0_Bt2Sal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_be_textbe_bt2sal_v0_Bt2Sal
 * Method:    translateToSal
 * Signature: (Ljava/lang/String;IIILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_be_textbe_bt2sal_v0_Bt2Sal_translateToSal
 (JNIEnv* env, jobject jobj, jstring strTree, jint iPriority, jint iBuff, jint iWithSets, jstring strSets, jstring strInit);

#ifdef __cplusplus
}
#endif
#endif
