/*
* generated by Xtext
*/
package org.be.textbe.bt2sal2.xtext.sal.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SalAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/be/textbe/bt2sal2/xtext/sal/parser/antlr/internal/InternalSal.tokens");
	}
}
