/*
* generated by Xtext
*/
package org.be.textbe;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ExpressionsUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.be.textbe.ui.internal.ExpressionsActivator.getInstance().getInjector("org.be.textbe.Expressions");
	}
	
}
