/*
 * generated by Xtext
 */
package org.be.textbe.bt2sal2.xtext.sal;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SalRuntimeModule extends org.be.textbe.bt2sal2.xtext.sal.AbstractSalRuntimeModule {

}
