/*
 * generated by Xtext
 */
package org.be.textbe;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ExpressionsRuntimeModule extends org.be.textbe.AbstractExpressionsRuntimeModule {

}
